<?
/**
 * DELIVERY_DHL_USA_WRITE_LOG
 */
define('DELIVERY_DHL_USA_WRITE_LOG', 0); // flag 'write to log'. use CDeliveryDHLUSA::__WriteToLog();

/**
 * DELIVERY_DHL_USA_CACHE_LIFETIME
 */
define('DELIVERY_DHL_USA_CACHE_LIFETIME', 2592000); // cache lifetime - 30 days (60*60*24*30);

/**
 * DELIVERY_DHL_USA_PACKAGE_TYPE_DEFAULT
 */
define('DELIVERY_DHL_USA_PACKAGE_TYPE_DEFAULT', 'CP');

/**
 * DELIVERY_DHL_USA_SERVER
 */
define('DELIVERY_DHL_USA_SERVER', 'www.dhl-usa.com');

/**
 * DELIVERY_DHL_USA_SERVER_PORT
 */
define('DELIVERY_DHL_USA_SERVER_PORT', 80);

/**
 * DELIVERY_DHL_USA_SERVER_PAGE
 */
define('DELIVERY_DHL_USA_SERVER_PAGE', '/ratecalculator/HandlerServlet');

/**
 * DELIVERY_DHL_USA_SERVER_METHOD
 */
define('DELIVERY_DHL_USA_SERVER_METHOD', 'POST');

/**
 * DELIVERY_DHL_USA_VALUE_CHECK_STRING
 */
define('DELIVERY_DHL_USA_VALUE_CHECK_STRING', 'Quote results');

/**
 * DELIVERY_UPS_ZONES_PHP_FILE
 */
define('DELIVERY_UPS_ZONES_PHP_FILE', 'ups/zones.php');

/**
 * DELIVERY_UPS_EXPORT_PHP_FILE
 */
define('DELIVERY_UPS_EXPORT_PHP_FILE', 'ups/export.php');

/**
 * SALE_DH_INITIALIZED
 */
define('SALE_DH_INITIALIZED', 1);

/**
 * DLSERVER
 */
define('DLSERVER', $arParams['DLSERVER']);

/**
 * DLPORT
 */
define('DLPORT', $arParams['DLPORT']);

/**
 * DLPATH
 */
define('DLPATH', $arParams['DLPATH']);

/**
 * DLMETHOD
 */
define('DLMETHOD', $arParams['DLMETHOD']);

/**
 * DLZIPFILE
 */
define('DLZIPFILE', $arParams["DLZIPFILE"]);

/**
 * ZIP_STEP_LENGTH
 */
define('ZIP_STEP_LENGTH', $step_length);

/**
 * LOC_STEP_LENGTH
 */
define('LOC_STEP_LENGTH', $step_length);

/**
 * COLUMNS_COUNT_FOR_SIMPLE_TEMPLATE
 */
define('COLUMNS_COUNT_FOR_SIMPLE_TEMPLATE', 3);

/**
 * PATH_TO_MOBILE_REPORTS
 */
define('PATH_TO_MOBILE_REPORTS', '/bitrix/admin/mobile/sale_reports_view.php');

/**
 * FPDF_FONTPATH
 */
define('FPDF_FONTPATH', $_SERVER["DOCUMENT_ROOT"]."/bitrix/fonts/");

/**
 * tFPDF_VERSION
 */
define('tFPDF_VERSION', '1.24');

/**
 * _TTF_MAC_HEADER
 */
define('_TTF_MAC_HEADER', false);

/**
 * GF_WORDS
 */
define('GF_WORDS', (1 << 0));

/**
 * GF_SCALE
 */
define('GF_SCALE', (1 << 3));

/**
 * GF_MORE
 */
define('GF_MORE', (1 << 5));

/**
 * GF_XYSCALE
 */
define('GF_XYSCALE', (1 << 6));

/**
 * GF_TWOBYTWO
 */
define('GF_TWOBYTWO', (1 << 7));

/**
 * SALE_TIME_LOCK_USER
 */
define('SALE_TIME_LOCK_USER', 600);

/**
 * SALE_DEBUG
 */
define('SALE_DEBUG', false);

/**
 * SALE_PROC_REC_NUM
 */
define('SALE_PROC_REC_NUM', 3);

/**
 * SALE_PROC_REC_ATTEMPTS
 */
define('SALE_PROC_REC_ATTEMPTS', 3);

/**
 * SALE_PROC_REC_TIME
 */
define('SALE_PROC_REC_TIME', 43200);

/**
 * SALE_PROC_REC_FREQUENCY
 */
define('SALE_PROC_REC_FREQUENCY', 7200);

/**
 * SALE_REPORT_OWNER_ID
 */
define('SALE_REPORT_OWNER_ID', 'sale');

/**
 * CACHED_b_sale_order
 */
define('CACHED_b_sale_order', 3600*24);

/**
 * SALE_VALUE_PRECISION
 */
define('SALE_VALUE_PRECISION', 2);

/**
 * SALE_WEIGHT_PRECISION
 */
define('SALE_WEIGHT_PRECISION', 3);

/**
 * BX_SALE_MENU_CATALOG_CLEAR
 */
define('BX_SALE_MENU_CATALOG_CLEAR', 'Y');

/**
 * NO_KEEP_STATISTIC
 */
define('NO_KEEP_STATISTIC', true);

/**
 * NOT_CHECK_PERMISSIONS
 */
define('NOT_CHECK_PERMISSIONS', true);

/**
 * ADMIN_MODULE_NAME
 */
define('ADMIN_MODULE_NAME', "sale");

/**
 * ADMIN_MODULE_ICON
 */
define('ADMIN_MODULE_ICON', "<a href=\"/bitrix/admin/sale_order.php?lang=".LANG."\"><img src=\"/bitrix/images/sale/sale.gif\" width=\"48\" height=\"48\" border=\"0\" alt=\"".GetMessage("SALE_ICON_TITLE")."\" title=\"".GetMessage("SALE_ICON_TITLE")."\"></a>");

/**
 * DELIVERY_CPCR_WRITE_LOG
 */
define('DELIVERY_CPCR_WRITE_LOG', 0); // flag 'write to log'. use CDeliveryCPCR::__WriteToLog();

/**
 * DELIVERY_CPCR_CACHE_LIFETIME
 */
define('DELIVERY_CPCR_CACHE_LIFETIME', 2592000); // cache lifetime - 30 days (60*60*24*30);

/**
 * DELIVERY_CPCR_CATEGORY_DEFAULT
 */
define('DELIVERY_CPCR_CATEGORY_DEFAULT', 8);

/**
 * DELIVERY_CPCR_PRICE_TARIFF
 */
define('DELIVERY_CPCR_PRICE_TARIFF', 0.0025);

/**
 * DELIVERY_CPCR_COUNTRY_DEFAULT
 */
define('DELIVERY_CPCR_COUNTRY_DEFAULT', '209|0');

/**
 * DELIVERY_CPCR_CITY_DEFAULT
 */
define('DELIVERY_CPCR_CITY_DEFAULT', '992|0');

/**
 * DELIVERY_CPCR_SERVER
 */
define('DELIVERY_CPCR_SERVER', 'spsr.ru');

/**
 * DELIVERY_CPCR_SERVER_PORT
 */
define('DELIVERY_CPCR_SERVER_PORT', 80);

/**
 * DELIVERY_CPCR_SERVER_PAGE
 */
define('DELIVERY_CPCR_SERVER_PAGE', '/cgi-bin/post09.pl?TARIFFCOMPUTE_2');

/**
 * DELIVERY_CPCR_SERVER_METHOD
 */
define('DELIVERY_CPCR_SERVER_METHOD', 'GET');

/**
 * DELIVERY_CPCR_SERVER_POST_FROM_REGION
 */
define('DELIVERY_CPCR_SERVER_POST_FROM_REGION', 'FromRegion');

/**
 * DELIVERY_CPCR_SERVER_POST_FROM_COUNTRY
 */
define('DELIVERY_CPCR_SERVER_POST_FROM_COUNTRY', 'FromCountry');

/**
 * DELIVERY_CPCR_SERVER_POST_FROM_CITY_NAME
 */
define('DELIVERY_CPCR_SERVER_POST_FROM_CITY_NAME', 'FromCity');

/**
 * DELIVERY_CPCR_SERVER_POST_FROM_CITY
 */
define('DELIVERY_CPCR_SERVER_POST_FROM_CITY', 'FromCity');

/**
 * DELIVERY_CPCR_SERVER_POST_WEIGHT
 */
define('DELIVERY_CPCR_SERVER_POST_WEIGHT', 'Weight');

/**
 * DELIVERY_CPCR_SERVER_POST_CATEGORY
 */
define('DELIVERY_CPCR_SERVER_POST_CATEGORY', 'Nature');

/**
 * DELIVERY_CPCR_SERVER_POST_PRICE
 */
define('DELIVERY_CPCR_SERVER_POST_PRICE', 'Amount');

/**
 * DELIVERY_CPCR_SERVER_POST_TO_COUNTRY
 */
define('DELIVERY_CPCR_SERVER_POST_TO_COUNTRY', 'Country');

/**
 * DELIVERY_CPCR_SERVER_POST_TO_REGION
 */
define('DELIVERY_CPCR_SERVER_POST_TO_REGION', 'ToRegion');

/**
 * DELIVERY_CPCR_SERVER_POST_TO_CITY_NAME
 */
define('DELIVERY_CPCR_SERVER_POST_TO_CITY_NAME', 'to_Cities_name');

/**
 * DELIVERY_CPCR_SERVER_POST_TO_CITY
 */
define('DELIVERY_CPCR_SERVER_POST_TO_CITY', 'ToCity');

/**
 * DELIVERY_CPCR_SERVER_POST_ADDITIONAL
 */
define('DELIVERY_CPCR_SERVER_POST_ADDITIONAL', 'Amount=0&AmountCheck=1&SMS=0&InHands=0&BeforeSignal=0&DuesOrder=0&PlatType=0&GabarythSum=60&GabarythB=0');

/**
 * DELIVERY_CPCR_VALUE_CHECK_STRING
 */
define('DELIVERY_CPCR_VALUE_CHECK_STRING', '"Total"');

/**
 * DELIVERY_EMS_CACHE_LIFETIME
 */
define('DELIVERY_EMS_CACHE_LIFETIME', 2592000); // cache lifetime - 30 days (60*60*24*30);

/**
 * DELIVERY_EMS_PRICE_TARIFF
 */
define('DELIVERY_EMS_PRICE_TARIFF', 0.01);

/**
 * DELIVERY_EMS_WRITE_LOG
 */
define('DELIVERY_EMS_WRITE_LOG', 0); // flag 'write to log'. use CDeliveryEMS::__WriteToLog();

/**
 * DELIVERY_RP_CSV_PATH
 */
define('DELIVERY_RP_CSV_PATH', $_SERVER['DOCUMENT_ROOT'].BX_ROOT.'/modules/sale/ru/delivery/rus_post');

/**
 * DELIVERY_RPF_CSV_PATH
 */
define('DELIVERY_RPF_CSV_PATH', $_SERVER['DOCUMENT_ROOT'].BX_ROOT.'/modules/sale/ru/delivery/rus_post_first');

/**
 * DELIVERY_RUSSIANPOST_WRITE_LOG
 */
define('DELIVERY_RUSSIANPOST_WRITE_LOG', 0); // flag 'write to log'. use CDeliveryRUSSIANPOST::__WriteToLog();

/**
 * DELIVERY_RUSSIANPOST_CACHE_LIFETIME
 */
define('DELIVERY_RUSSIANPOST_CACHE_LIFETIME', 2592000); // cache lifetime - 30 days (60*60*24*30);

/**
 * DELIVERY_RUSSIANPOST_CATEGORY_DEFAULT
 */
define('DELIVERY_RUSSIANPOST_CATEGORY_DEFAULT', 23);

/**
 * DELIVERY_RUSSIANPOST_PRICE_TARIFF
 */
define('DELIVERY_RUSSIANPOST_PRICE_TARIFF', 0.03);

/**
 * DELIVERY_RUSSIANPOST_PRICE_TARIFF_1
 */
define('DELIVERY_RUSSIANPOST_PRICE_TARIFF_1', 0.04);

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_CATEGORY
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_CATEGORY', 'viewPost');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_CATEGORY_NAME
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_CATEGORY_NAME', 'viewPostName');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_PROFILE
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_PROFILE', 'typePost');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_PROFILE_NAME
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_PROFILE_NAME', 'typePostName');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_ZIP
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_ZIP', 'postOfficeId');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_WEIGHT
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_WEIGHT', 'weight');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_PRICE
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_PRICE', 'value1');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_COUNTRY
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_COUNTRY', 'countryCode');

/**
 * DELIVERY_RUSSIANPOST_SERVER_POST_COUNTRY_NAME
 */
define('DELIVERY_RUSSIANPOST_SERVER_POST_COUNTRY_NAME', 'countryCodeName');

/**
 * DELIVERY_RUSSIANPOST_SERVER
 */
define('DELIVERY_RUSSIANPOST_SERVER', 'www.russianpost.ru');

/**
 * DELIVERY_RUSSIANPOST_SERVER_PORT
 */
define('DELIVERY_RUSSIANPOST_SERVER_PORT', 80);

/**
 * DELIVERY_RUSSIANPOST_SERVER_PAGE
 */
define('DELIVERY_RUSSIANPOST_SERVER_PAGE', '/autotarif/Autotarif.aspx');

/**
 * DELIVERY_RUSSIANPOST_SERVER_METHOD
 */
define('DELIVERY_RUSSIANPOST_SERVER_METHOD', 'GET');

/**
 * DELIVERY_RUSSIANPOST_SERVER_METHOD_CAPTHA
 */
define('DELIVERY_RUSSIANPOST_SERVER_METHOD_CAPTHA', 'POST');

/**
 * DELIVERY_RUSSIANPOST_VALUE_CHECK_STRING
 */
define('DELIVERY_RUSSIANPOST_VALUE_CHECK_STRING', '<span id="TarifValue">');

/**
 * DELIVERY_RUSSIANPOST_VALUE_CAPTHA_STRING
 */
define('DELIVERY_RUSSIANPOST_VALUE_CAPTHA_STRING', '<input id="key"');

/**
 * NO_AGENT_CHECK
 */
define('NO_AGENT_CHECK', true);

/**
 * NO_AGENT_STATISTIC
 */
define('NO_AGENT_STATISTIC', true);

/**
 * DisableEventsCheck
 */
define('DisableEventsCheck', true);


?>